// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: protobuf/order/order.proto

package order

import (
	common "github.com/BullionBear/sequex/internal/model/protobuf/common"
	product "github.com/BullionBear/sequex/internal/model/protobuf/product"
	user "github.com/BullionBear/sequex/internal/model/protobuf/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status enum
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_CONFIRMED   OrderStatus = 2
	OrderStatus_ORDER_STATUS_PROCESSING  OrderStatus = 3
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 4
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 5
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 6
	OrderStatus_ORDER_STATUS_REFUNDED    OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_CONFIRMED",
		3: "ORDER_STATUS_PROCESSING",
		4: "ORDER_STATUS_SHIPPED",
		5: "ORDER_STATUS_DELIVERED",
		6: "ORDER_STATUS_CANCELLED",
		7: "ORDER_STATUS_REFUNDED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_CONFIRMED":   2,
		"ORDER_STATUS_PROCESSING":  3,
		"ORDER_STATUS_SHIPPED":     4,
		"ORDER_STATUS_DELIVERED":   5,
		"ORDER_STATUS_CANCELLED":   6,
		"ORDER_STATUS_REFUNDED":    7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_order_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_protobuf_order_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{0}
}

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_COMPLETED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_COMPLETED":   3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_REFUNDED":    5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_order_order_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_protobuf_order_order_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{1}
}

// Order entity
type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OrderNumber    string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Customer       *user.User             `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Status         OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Items          []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	Shipping       *OrderShipping         `protobuf:"bytes,6,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Payment        *OrderPayment          `protobuf:"bytes,7,opt,name=payment,proto3" json:"payment,omitempty"`
	TotalAmount    float64                `protobuf:"fixed64,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TaxAmount      float64                `protobuf:"fixed64,9,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	ShippingAmount float64                `protobuf:"fixed64,10,opt,name=shipping_amount,json=shippingAmount,proto3" json:"shipping_amount,omitempty"`
	DiscountAmount float64                `protobuf:"fixed64,11,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_protobuf_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Order) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *Order) GetCustomer() *user.User {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetShipping() *OrderShipping {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *Order) GetPayment() *OrderPayment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *Order) GetShippingAmount() float64 {
	if x != nil {
		return x.ShippingAmount
	}
	return 0
}

func (x *Order) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

// Order item
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *product.Product       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_protobuf_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProduct() *product.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderItem) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Order shipping information
type OrderShipping struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AddressLine1      string                 `protobuf:"bytes,1,opt,name=address_line1,json=addressLine1,proto3" json:"address_line1,omitempty"`
	AddressLine2      string                 `protobuf:"bytes,2,opt,name=address_line2,json=addressLine2,proto3" json:"address_line2,omitempty"`
	City              string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State             string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode        string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country           string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Phone             string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,8,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier           string                 `protobuf:"bytes,9,opt,name=carrier,proto3" json:"carrier,omitempty"`
	EstimatedDelivery string                 `protobuf:"bytes,10,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderShipping) Reset() {
	*x = OrderShipping{}
	mi := &file_protobuf_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderShipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderShipping) ProtoMessage() {}

func (x *OrderShipping) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderShipping.ProtoReflect.Descriptor instead.
func (*OrderShipping) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderShipping) GetAddressLine1() string {
	if x != nil {
		return x.AddressLine1
	}
	return ""
}

func (x *OrderShipping) GetAddressLine2() string {
	if x != nil {
		return x.AddressLine2
	}
	return ""
}

func (x *OrderShipping) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderShipping) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OrderShipping) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *OrderShipping) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *OrderShipping) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderShipping) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *OrderShipping) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *OrderShipping) GetEstimatedDelivery() string {
	if x != nil {
		return x.EstimatedDelivery
	}
	return ""
}

// Order payment information
type OrderPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethod string                 `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=order.PaymentStatus" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentDate   string                 `protobuf:"bytes,6,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayment) Reset() {
	*x = OrderPayment{}
	mi := &file_protobuf_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayment) ProtoMessage() {}

func (x *OrderPayment) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayment.ProtoReflect.Descriptor instead.
func (*OrderPayment) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPayment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderPayment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *OrderPayment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *OrderPayment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderPayment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderPayment) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

// Create order request
type CreateOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CustomerId    string                    `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items         []*CreateOrderItemRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Shipping      *OrderShipping            `protobuf:"bytes,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
	PaymentMethod string                    `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CouponCode    string                    `protobuf:"bytes,5,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetShipping() *OrderShipping {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *CreateOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateOrderRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

// Create order item request
type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderItemRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Create order response
type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_protobuf_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get order request
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Get order response
type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_protobuf_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Update order request
type UpdateOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status         OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Shipping       *OrderShipping         `protobuf:"bytes,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,4,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderRequest) GetShipping() *OrderShipping {
	if x != nil {
		return x.Shipping
	}
	return nil
}

func (x *UpdateOrderRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

// Update order response
type UpdateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	mi := &file_protobuf_order_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateOrderResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Cancel order request
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{11}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Cancel order response
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_protobuf_order_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{12}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// List orders request
type ListOrdersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	CustomerId    string                    `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        OrderStatus               `protobuf:"varint,3,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	DateFrom      string                    `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                    `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListOrdersRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

// List orders response
type ListOrdersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Orders        []*Order                   `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *common.ErrorResponse      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_protobuf_order_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrdersResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get order history request
type GetOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderHistoryRequest) Reset() {
	*x = GetOrderHistoryRequest{}
	mi := &file_protobuf_order_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryRequest) ProtoMessage() {}

func (x *GetOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderHistoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Order history entry
type OrderHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedBy     *user.User             `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHistoryEntry) Reset() {
	*x = OrderHistoryEntry{}
	mi := &file_protobuf_order_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHistoryEntry) ProtoMessage() {}

func (x *OrderHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHistoryEntry.ProtoReflect.Descriptor instead.
func (*OrderHistoryEntry) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{16}
}

func (x *OrderHistoryEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OrderHistoryEntry) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderHistoryEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrderHistoryEntry) GetUpdatedBy() *user.User {
	if x != nil {
		return x.UpdatedBy
	}
	return nil
}

// Get order history response
type GetOrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*OrderHistoryEntry   `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderHistoryResponse) Reset() {
	*x = GetOrderHistoryResponse{}
	mi := &file_protobuf_order_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryResponse) ProtoMessage() {}

func (x *GetOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_order_order_proto_rawDescGZIP(), []int{17}
}

func (x *GetOrderHistoryResponse) GetHistory() []*OrderHistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetOrderHistoryResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_protobuf_order_order_proto protoreflect.FileDescriptor

const file_protobuf_order_order_proto_rawDesc = "" +
	"\n" +
	"\x1aprotobuf/order/order.proto\x12\x05order\x1a\x1cprotobuf/common/common.proto\x1a\x18protobuf/user/user.proto\x1a\x1eprotobuf/product/product.proto\"\xc9\x03\n" +
	"\x05Order\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12&\n" +
	"\bcustomer\x18\x03 \x01(\v2\n" +
	".user.UserR\bcustomer\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12&\n" +
	"\x05items\x18\x05 \x03(\v2\x10.order.OrderItemR\x05items\x120\n" +
	"\bshipping\x18\x06 \x01(\v2\x14.order.OrderShippingR\bshipping\x12-\n" +
	"\apayment\x18\a \x01(\v2\x13.order.OrderPaymentR\apayment\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\t \x01(\x01R\ttaxAmount\x12'\n" +
	"\x0fshipping_amount\x18\n" +
	" \x01(\x01R\x0eshippingAmount\x12'\n" +
	"\x0fdiscount_amount\x18\v \x01(\x01R\x0ediscountAmount\"\xad\x01\n" +
	"\tOrderItem\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\"\xc6\x02\n" +
	"\rOrderShipping\x12#\n" +
	"\raddress_line1\x18\x01 \x01(\tR\faddressLine1\x12#\n" +
	"\raddress_line2\x18\x02 \x01(\tR\faddressLine2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12'\n" +
	"\x0ftracking_number\x18\b \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\t \x01(\tR\acarrier\x12-\n" +
	"\x12estimated_delivery\x18\n" +
	" \x01(\tR\x11estimatedDelivery\"\xe1\x01\n" +
	"\fOrderPayment\x12%\n" +
	"\x0epayment_method\x18\x01 \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.order.PaymentStatusR\x06status\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\fpayment_date\x18\x06 \x01(\tR\vpaymentDate\"\xe4\x01\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.order.CreateOrderItemRequestR\x05items\x120\n" +
	"\bshipping\x18\x03 \x01(\v2\x14.order.OrderShippingR\bshipping\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vcoupon_code\x18\x05 \x01(\tR\n" +
	"couponCode\"m\n" +
	"\x16CreateOrderItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\"f\n" +
	"\x13CreateOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"c\n" +
	"\x10GetOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xb6\x01\n" +
	"\x12UpdateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\x120\n" +
	"\bshipping\x18\x03 \x01(\v2\x14.order.OrderShippingR\bshipping\x12'\n" +
	"\x0ftracking_number\x18\x04 \x01(\tR\x0etrackingNumber\"f\n" +
	"\x13UpdateOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"G\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\\\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xd1\x01\n" +
	"\x11ListOrdersRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1b\n" +
	"\tdate_from\x18\x04 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x05 \x01(\tR\x06dateTo\"\xa3\x01\n" +
	"\x12ListOrdersResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"3\n" +
	"\x16GetOrderHistoryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xaa\x01\n" +
	"\x11OrderHistoryEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\v2\n" +
	".user.UserR\tupdatedBy\"z\n" +
	"\x17GetOrderHistoryResponse\x122\n" +
	"\ahistory\x18\x01 \x03(\v2\x18.order.OrderHistoryEntryR\ahistory\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error*\xeb\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CONFIRMED\x10\x02\x12\x1b\n" +
	"\x17ORDER_STATUS_PROCESSING\x10\x03\x12\x18\n" +
	"\x14ORDER_STATUS_SHIPPED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x06\x12\x19\n" +
	"\x15ORDER_STATUS_REFUNDED\x10\a*\xc0\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x052\xb2\x03\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12;\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12D\n" +
	"\vUpdateOrder\x12\x19.order.UpdateOrderRequest\x1a\x1a.order.UpdateOrderResponse\x12D\n" +
	"\vCancelOrder\x12\x19.order.CancelOrderRequest\x1a\x1a.order.CancelOrderResponse\x12A\n" +
	"\n" +
	"ListOrders\x12\x18.order.ListOrdersRequest\x1a\x19.order.ListOrdersResponse\x12P\n" +
	"\x0fGetOrderHistory\x12\x1d.order.GetOrderHistoryRequest\x1a\x1e.order.GetOrderHistoryResponseB=Z;github.com/BullionBear/sequex/internal/model/protobuf/orderb\x06proto3"

var (
	file_protobuf_order_order_proto_rawDescOnce sync.Once
	file_protobuf_order_order_proto_rawDescData []byte
)

func file_protobuf_order_order_proto_rawDescGZIP() []byte {
	file_protobuf_order_order_proto_rawDescOnce.Do(func() {
		file_protobuf_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_order_order_proto_rawDesc), len(file_protobuf_order_order_proto_rawDesc)))
	})
	return file_protobuf_order_order_proto_rawDescData
}

var file_protobuf_order_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protobuf_order_order_proto_goTypes = []any{
	(OrderStatus)(0),                  // 0: order.OrderStatus
	(PaymentStatus)(0),                // 1: order.PaymentStatus
	(*Order)(nil),                     // 2: order.Order
	(*OrderItem)(nil),                 // 3: order.OrderItem
	(*OrderShipping)(nil),             // 4: order.OrderShipping
	(*OrderPayment)(nil),              // 5: order.OrderPayment
	(*CreateOrderRequest)(nil),        // 6: order.CreateOrderRequest
	(*CreateOrderItemRequest)(nil),    // 7: order.CreateOrderItemRequest
	(*CreateOrderResponse)(nil),       // 8: order.CreateOrderResponse
	(*GetOrderRequest)(nil),           // 9: order.GetOrderRequest
	(*GetOrderResponse)(nil),          // 10: order.GetOrderResponse
	(*UpdateOrderRequest)(nil),        // 11: order.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),       // 12: order.UpdateOrderResponse
	(*CancelOrderRequest)(nil),        // 13: order.CancelOrderRequest
	(*CancelOrderResponse)(nil),       // 14: order.CancelOrderResponse
	(*ListOrdersRequest)(nil),         // 15: order.ListOrdersRequest
	(*ListOrdersResponse)(nil),        // 16: order.ListOrdersResponse
	(*GetOrderHistoryRequest)(nil),    // 17: order.GetOrderHistoryRequest
	(*OrderHistoryEntry)(nil),         // 18: order.OrderHistoryEntry
	(*GetOrderHistoryResponse)(nil),   // 19: order.GetOrderHistoryResponse
	(*common.Metadata)(nil),           // 20: common.Metadata
	(*user.User)(nil),                 // 21: user.User
	(*product.Product)(nil),           // 22: product.Product
	(*common.ErrorResponse)(nil),      // 23: common.ErrorResponse
	(*common.PaginationRequest)(nil),  // 24: common.PaginationRequest
	(*common.PaginationResponse)(nil), // 25: common.PaginationResponse
}
var file_protobuf_order_order_proto_depIdxs = []int32{
	20, // 0: order.Order.metadata:type_name -> common.Metadata
	21, // 1: order.Order.customer:type_name -> user.User
	0,  // 2: order.Order.status:type_name -> order.OrderStatus
	3,  // 3: order.Order.items:type_name -> order.OrderItem
	4,  // 4: order.Order.shipping:type_name -> order.OrderShipping
	5,  // 5: order.Order.payment:type_name -> order.OrderPayment
	22, // 6: order.OrderItem.product:type_name -> product.Product
	1,  // 7: order.OrderPayment.status:type_name -> order.PaymentStatus
	7,  // 8: order.CreateOrderRequest.items:type_name -> order.CreateOrderItemRequest
	4,  // 9: order.CreateOrderRequest.shipping:type_name -> order.OrderShipping
	2,  // 10: order.CreateOrderResponse.order:type_name -> order.Order
	23, // 11: order.CreateOrderResponse.error:type_name -> common.ErrorResponse
	2,  // 12: order.GetOrderResponse.order:type_name -> order.Order
	23, // 13: order.GetOrderResponse.error:type_name -> common.ErrorResponse
	0,  // 14: order.UpdateOrderRequest.status:type_name -> order.OrderStatus
	4,  // 15: order.UpdateOrderRequest.shipping:type_name -> order.OrderShipping
	2,  // 16: order.UpdateOrderResponse.order:type_name -> order.Order
	23, // 17: order.UpdateOrderResponse.error:type_name -> common.ErrorResponse
	23, // 18: order.CancelOrderResponse.error:type_name -> common.ErrorResponse
	24, // 19: order.ListOrdersRequest.pagination:type_name -> common.PaginationRequest
	0,  // 20: order.ListOrdersRequest.status:type_name -> order.OrderStatus
	2,  // 21: order.ListOrdersResponse.orders:type_name -> order.Order
	25, // 22: order.ListOrdersResponse.pagination:type_name -> common.PaginationResponse
	23, // 23: order.ListOrdersResponse.error:type_name -> common.ErrorResponse
	0,  // 24: order.OrderHistoryEntry.status:type_name -> order.OrderStatus
	21, // 25: order.OrderHistoryEntry.updated_by:type_name -> user.User
	18, // 26: order.GetOrderHistoryResponse.history:type_name -> order.OrderHistoryEntry
	23, // 27: order.GetOrderHistoryResponse.error:type_name -> common.ErrorResponse
	6,  // 28: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	9,  // 29: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	11, // 30: order.OrderService.UpdateOrder:input_type -> order.UpdateOrderRequest
	13, // 31: order.OrderService.CancelOrder:input_type -> order.CancelOrderRequest
	15, // 32: order.OrderService.ListOrders:input_type -> order.ListOrdersRequest
	17, // 33: order.OrderService.GetOrderHistory:input_type -> order.GetOrderHistoryRequest
	8,  // 34: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	10, // 35: order.OrderService.GetOrder:output_type -> order.GetOrderResponse
	12, // 36: order.OrderService.UpdateOrder:output_type -> order.UpdateOrderResponse
	14, // 37: order.OrderService.CancelOrder:output_type -> order.CancelOrderResponse
	16, // 38: order.OrderService.ListOrders:output_type -> order.ListOrdersResponse
	19, // 39: order.OrderService.GetOrderHistory:output_type -> order.GetOrderHistoryResponse
	34, // [34:40] is the sub-list for method output_type
	28, // [28:34] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_protobuf_order_order_proto_init() }
func file_protobuf_order_order_proto_init() {
	if File_protobuf_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_order_order_proto_rawDesc), len(file_protobuf_order_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_order_order_proto_goTypes,
		DependencyIndexes: file_protobuf_order_order_proto_depIdxs,
		EnumInfos:         file_protobuf_order_order_proto_enumTypes,
		MessageInfos:      file_protobuf_order_order_proto_msgTypes,
	}.Build()
	File_protobuf_order_order_proto = out.File
	file_protobuf_order_order_proto_goTypes = nil
	file_protobuf_order_order_proto_depIdxs = nil
}
