// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: proto/product/product.proto

package product

import (
	common "github.com/yitech/protolayout/protobuf/proto/common"
	user "github.com/yitech/protolayout/protobuf/proto/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product category enum
type ProductCategory int32

const (
	ProductCategory_PRODUCT_CATEGORY_UNSPECIFIED ProductCategory = 0
	ProductCategory_PRODUCT_CATEGORY_ELECTRONICS ProductCategory = 1
	ProductCategory_PRODUCT_CATEGORY_CLOTHING    ProductCategory = 2
	ProductCategory_PRODUCT_CATEGORY_BOOKS       ProductCategory = 3
	ProductCategory_PRODUCT_CATEGORY_HOME        ProductCategory = 4
	ProductCategory_PRODUCT_CATEGORY_SPORTS      ProductCategory = 5
)

// Enum value maps for ProductCategory.
var (
	ProductCategory_name = map[int32]string{
		0: "PRODUCT_CATEGORY_UNSPECIFIED",
		1: "PRODUCT_CATEGORY_ELECTRONICS",
		2: "PRODUCT_CATEGORY_CLOTHING",
		3: "PRODUCT_CATEGORY_BOOKS",
		4: "PRODUCT_CATEGORY_HOME",
		5: "PRODUCT_CATEGORY_SPORTS",
	}
	ProductCategory_value = map[string]int32{
		"PRODUCT_CATEGORY_UNSPECIFIED": 0,
		"PRODUCT_CATEGORY_ELECTRONICS": 1,
		"PRODUCT_CATEGORY_CLOTHING":    2,
		"PRODUCT_CATEGORY_BOOKS":       3,
		"PRODUCT_CATEGORY_HOME":        4,
		"PRODUCT_CATEGORY_SPORTS":      5,
	}
)

func (x ProductCategory) Enum() *ProductCategory {
	p := new(ProductCategory)
	*p = x
	return p
}

func (x ProductCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_product_proto_enumTypes[0].Descriptor()
}

func (ProductCategory) Type() protoreflect.EnumType {
	return &file_proto_product_product_proto_enumTypes[0]
}

func (x ProductCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductCategory.Descriptor instead.
func (ProductCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

// Product status enum
type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNSPECIFIED  ProductStatus = 0
	ProductStatus_PRODUCT_STATUS_AVAILABLE    ProductStatus = 1
	ProductStatus_PRODUCT_STATUS_OUT_OF_STOCK ProductStatus = 2
	ProductStatus_PRODUCT_STATUS_DISCONTINUED ProductStatus = 3
	ProductStatus_PRODUCT_STATUS_DRAFT        ProductStatus = 4
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNSPECIFIED",
		1: "PRODUCT_STATUS_AVAILABLE",
		2: "PRODUCT_STATUS_OUT_OF_STOCK",
		3: "PRODUCT_STATUS_DISCONTINUED",
		4: "PRODUCT_STATUS_DRAFT",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNSPECIFIED":  0,
		"PRODUCT_STATUS_AVAILABLE":    1,
		"PRODUCT_STATUS_OUT_OF_STOCK": 2,
		"PRODUCT_STATUS_DISCONTINUED": 3,
		"PRODUCT_STATUS_DRAFT":        4,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_product_product_proto_enumTypes[1].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_proto_product_product_proto_enumTypes[1]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

// Product entity
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      ProductCategory        `protobuf:"varint,5,opt,name=category,proto3,enum=product.ProductCategory" json:"category,omitempty"`
	Status        ProductStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Inventory     *ProductInventory      `protobuf:"bytes,8,opt,name=inventory,proto3" json:"inventory,omitempty"`
	CreatedByUser *user.User             `protobuf:"bytes,9,opt,name=created_by_user,json=createdByUser,proto3" json:"created_by_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategory() ProductCategory {
	if x != nil {
		return x.Category
	}
	return ProductCategory_PRODUCT_CATEGORY_UNSPECIFIED
}

func (x *Product) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetInventory() *ProductInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *Product) GetCreatedByUser() *user.User {
	if x != nil {
		return x.CreatedByUser
	}
	return nil
}

// Product inventory information
type ProductInventory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Quantity          int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedQuantity  int32                  `protobuf:"varint,2,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	WarehouseLocation string                 `protobuf:"bytes,3,opt,name=warehouse_location,json=warehouseLocation,proto3" json:"warehouse_location,omitempty"`
	ReorderThreshold  float64                `protobuf:"fixed64,4,opt,name=reorder_threshold,json=reorderThreshold,proto3" json:"reorder_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProductInventory) Reset() {
	*x = ProductInventory{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInventory) ProtoMessage() {}

func (x *ProductInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInventory.ProtoReflect.Descriptor instead.
func (*ProductInventory) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductInventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductInventory) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *ProductInventory) GetWarehouseLocation() string {
	if x != nil {
		return x.WarehouseLocation
	}
	return ""
}

func (x *ProductInventory) GetReorderThreshold() float64 {
	if x != nil {
		return x.ReorderThreshold
	}
	return 0
}

// Product review
type ProductReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Reviewer      *user.User             `protobuf:"bytes,3,opt,name=reviewer,proto3" json:"reviewer,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReview) Reset() {
	*x = ProductReview{}
	mi := &file_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReview) ProtoMessage() {}

func (x *ProductReview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReview.ProtoReflect.Descriptor instead.
func (*ProductReview) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductReview) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProductReview) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductReview) GetReviewer() *user.User {
	if x != nil {
		return x.Reviewer
	}
	return nil
}

func (x *ProductReview) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductReview) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ProductReview) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

// Create product request
type CreateProductRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price           float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category        ProductCategory        `protobuf:"varint,4,opt,name=category,proto3,enum=product.ProductCategory" json:"category,omitempty"`
	Tags            []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Inventory       *ProductInventory      `protobuf:"bytes,6,opt,name=inventory,proto3" json:"inventory,omitempty"`
	CreatedByUserId string                 `protobuf:"bytes,7,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCategory() ProductCategory {
	if x != nil {
		return x.Category
	}
	return ProductCategory_PRODUCT_CATEGORY_UNSPECIFIED
}

func (x *CreateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateProductRequest) GetInventory() *ProductInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *CreateProductRequest) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

// Create product response
type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *CreateProductResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get product request
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// Get product response
type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetProductResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Update product request
type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      ProductCategory        `protobuf:"varint,5,opt,name=category,proto3,enum=product.ProductCategory" json:"category,omitempty"`
	Status        ProductStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Inventory     *ProductInventory      `protobuf:"bytes,8,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetCategory() ProductCategory {
	if x != nil {
		return x.Category
	}
	return ProductCategory_PRODUCT_CATEGORY_UNSPECIFIED
}

func (x *UpdateProductRequest) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *UpdateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateProductRequest) GetInventory() *ProductInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

// Update product response
type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *UpdateProductResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Delete product request
type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// Delete product response
type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.ErrorResponse  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProductResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// List products request
type ListProductsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Category      ProductCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=product.ProductCategory" json:"category,omitempty"`
	Status        ProductStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`
	SearchQuery   string                    `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	MinPrice      float64                   `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                   `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_product_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{11}
}

func (x *ListProductsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProductsRequest) GetCategory() ProductCategory {
	if x != nil {
		return x.Category
	}
	return ProductCategory_PRODUCT_CATEGORY_UNSPECIFIED
}

func (x *ListProductsRequest) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *ListProductsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListProductsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListProductsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

// List products response
type ListProductsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Products      []*Product                 `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *common.ErrorResponse      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_product_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{12}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProductsResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get product reviews request
type GetProductReviewsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ProductId     string                    `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReviewsRequest) Reset() {
	*x = GetProductReviewsRequest{}
	mi := &file_proto_product_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReviewsRequest) ProtoMessage() {}

func (x *GetProductReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetProductReviewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductReviewsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductReviewsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Get product reviews response
type GetProductReviewsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Reviews       []*ProductReview           `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *common.ErrorResponse      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReviewsResponse) Reset() {
	*x = GetProductReviewsResponse{}
	mi := &file_proto_product_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReviewsResponse) ProtoMessage() {}

func (x *GetProductReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetProductReviewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{14}
}

func (x *GetProductReviewsResponse) GetReviews() []*ProductReview {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *GetProductReviewsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetProductReviewsResponse) GetError() *common.ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\aproduct\x1a\x19proto/common/common.proto\x1a\x15proto/user/user.proto\"\xea\x02\n" +
	"\aProduct\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x124\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x18.product.ProductCategoryR\bcategory\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.product.ProductStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x127\n" +
	"\tinventory\x18\b \x01(\v2\x19.product.ProductInventoryR\tinventory\x122\n" +
	"\x0fcreated_by_user\x18\t \x01(\v2\n" +
	".user.UserR\rcreatedByUser\"\xb7\x01\n" +
	"\x10ProductInventory\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12+\n" +
	"\x11reserved_quantity\x18\x02 \x01(\x05R\x10reservedQuantity\x12-\n" +
	"\x12warehouse_location\x18\x03 \x01(\tR\x11warehouseLocation\x12+\n" +
	"\x11reorder_threshold\x18\x04 \x01(\x01R\x10reorderThreshold\"\xce\x01\n" +
	"\rProductReview\x12,\n" +
	"\bmetadata\x18\x01 \x01(\v2\x10.common.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12&\n" +
	"\breviewer\x18\x03 \x01(\v2\n" +
	".user.UserR\breviewer\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\"\x92\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x124\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x18.product.ProductCategoryR\bcategory\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x127\n" +
	"\tinventory\x18\x06 \x01(\v2\x19.product.ProductInventoryR\tinventory\x12+\n" +
	"\x12created_by_user_id\x18\a \x01(\tR\x0fcreatedByUserId\"p\n" +
	"\x15CreateProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"m\n" +
	"\x12GetProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xb4\x02\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x124\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x18.product.ProductCategoryR\bcategory\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.product.ProductStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x127\n" +
	"\tinventory\x18\b \x01(\v2\x19.product.ProductInventoryR\tinventory\"p\n" +
	"\x15UpdateProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"5\n" +
	"\x14DeleteProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"^\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\x93\x02\n" +
	"\x13ListProductsRequest\x129\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x124\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x18.product.ProductCategoryR\bcategory\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.product.ProductStatusR\x06status\x12!\n" +
	"\fsearch_query\x18\x04 \x01(\tR\vsearchQuery\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x01R\bmaxPrice\"\xad\x01\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"t\n" +
	"\x18GetProductReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\xb6\x01\n" +
	"\x19GetProductReviewsResponse\x120\n" +
	"\areviews\x18\x01 \x03(\v2\x16.product.ProductReviewR\areviews\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error*\xc8\x01\n" +
	"\x0fProductCategory\x12 \n" +
	"\x1cPRODUCT_CATEGORY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPRODUCT_CATEGORY_ELECTRONICS\x10\x01\x12\x1d\n" +
	"\x19PRODUCT_CATEGORY_CLOTHING\x10\x02\x12\x1a\n" +
	"\x16PRODUCT_CATEGORY_BOOKS\x10\x03\x12\x19\n" +
	"\x15PRODUCT_CATEGORY_HOME\x10\x04\x12\x1b\n" +
	"\x17PRODUCT_CATEGORY_SPORTS\x10\x05*\xa9\x01\n" +
	"\rProductStatus\x12\x1e\n" +
	"\x1aPRODUCT_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PRODUCT_STATUS_AVAILABLE\x10\x01\x12\x1f\n" +
	"\x1bPRODUCT_STATUS_OUT_OF_STOCK\x10\x02\x12\x1f\n" +
	"\x1bPRODUCT_STATUS_DISCONTINUED\x10\x03\x12\x18\n" +
	"\x14PRODUCT_STATUS_DRAFT\x10\x042\xf0\x03\n" +
	"\x0eProductService\x12N\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x1e.product.CreateProductResponse\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\x12N\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x1e.product.UpdateProductResponse\x12N\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12Z\n" +
	"\x11GetProductReviews\x12!.product.GetProductReviewsRequest\x1a\".product.GetProductReviewsResponseB6Z4github.com/yitech/protolayout/protobuf/proto/productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_product_product_proto_goTypes = []any{
	(ProductCategory)(0),              // 0: product.ProductCategory
	(ProductStatus)(0),                // 1: product.ProductStatus
	(*Product)(nil),                   // 2: product.Product
	(*ProductInventory)(nil),          // 3: product.ProductInventory
	(*ProductReview)(nil),             // 4: product.ProductReview
	(*CreateProductRequest)(nil),      // 5: product.CreateProductRequest
	(*CreateProductResponse)(nil),     // 6: product.CreateProductResponse
	(*GetProductRequest)(nil),         // 7: product.GetProductRequest
	(*GetProductResponse)(nil),        // 8: product.GetProductResponse
	(*UpdateProductRequest)(nil),      // 9: product.UpdateProductRequest
	(*UpdateProductResponse)(nil),     // 10: product.UpdateProductResponse
	(*DeleteProductRequest)(nil),      // 11: product.DeleteProductRequest
	(*DeleteProductResponse)(nil),     // 12: product.DeleteProductResponse
	(*ListProductsRequest)(nil),       // 13: product.ListProductsRequest
	(*ListProductsResponse)(nil),      // 14: product.ListProductsResponse
	(*GetProductReviewsRequest)(nil),  // 15: product.GetProductReviewsRequest
	(*GetProductReviewsResponse)(nil), // 16: product.GetProductReviewsResponse
	(*common.Metadata)(nil),           // 17: common.Metadata
	(*user.User)(nil),                 // 18: user.User
	(*common.ErrorResponse)(nil),      // 19: common.ErrorResponse
	(*common.PaginationRequest)(nil),  // 20: common.PaginationRequest
	(*common.PaginationResponse)(nil), // 21: common.PaginationResponse
}
var file_proto_product_product_proto_depIdxs = []int32{
	17, // 0: product.Product.metadata:type_name -> common.Metadata
	0,  // 1: product.Product.category:type_name -> product.ProductCategory
	1,  // 2: product.Product.status:type_name -> product.ProductStatus
	3,  // 3: product.Product.inventory:type_name -> product.ProductInventory
	18, // 4: product.Product.created_by_user:type_name -> user.User
	17, // 5: product.ProductReview.metadata:type_name -> common.Metadata
	18, // 6: product.ProductReview.reviewer:type_name -> user.User
	0,  // 7: product.CreateProductRequest.category:type_name -> product.ProductCategory
	3,  // 8: product.CreateProductRequest.inventory:type_name -> product.ProductInventory
	2,  // 9: product.CreateProductResponse.product:type_name -> product.Product
	19, // 10: product.CreateProductResponse.error:type_name -> common.ErrorResponse
	2,  // 11: product.GetProductResponse.product:type_name -> product.Product
	19, // 12: product.GetProductResponse.error:type_name -> common.ErrorResponse
	0,  // 13: product.UpdateProductRequest.category:type_name -> product.ProductCategory
	1,  // 14: product.UpdateProductRequest.status:type_name -> product.ProductStatus
	3,  // 15: product.UpdateProductRequest.inventory:type_name -> product.ProductInventory
	2,  // 16: product.UpdateProductResponse.product:type_name -> product.Product
	19, // 17: product.UpdateProductResponse.error:type_name -> common.ErrorResponse
	19, // 18: product.DeleteProductResponse.error:type_name -> common.ErrorResponse
	20, // 19: product.ListProductsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 20: product.ListProductsRequest.category:type_name -> product.ProductCategory
	1,  // 21: product.ListProductsRequest.status:type_name -> product.ProductStatus
	2,  // 22: product.ListProductsResponse.products:type_name -> product.Product
	21, // 23: product.ListProductsResponse.pagination:type_name -> common.PaginationResponse
	19, // 24: product.ListProductsResponse.error:type_name -> common.ErrorResponse
	20, // 25: product.GetProductReviewsRequest.pagination:type_name -> common.PaginationRequest
	4,  // 26: product.GetProductReviewsResponse.reviews:type_name -> product.ProductReview
	21, // 27: product.GetProductReviewsResponse.pagination:type_name -> common.PaginationResponse
	19, // 28: product.GetProductReviewsResponse.error:type_name -> common.ErrorResponse
	5,  // 29: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	7,  // 30: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	9,  // 31: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	11, // 32: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	13, // 33: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	15, // 34: product.ProductService.GetProductReviews:input_type -> product.GetProductReviewsRequest
	6,  // 35: product.ProductService.CreateProduct:output_type -> product.CreateProductResponse
	8,  // 36: product.ProductService.GetProduct:output_type -> product.GetProductResponse
	10, // 37: product.ProductService.UpdateProduct:output_type -> product.UpdateProductResponse
	12, // 38: product.ProductService.DeleteProduct:output_type -> product.DeleteProductResponse
	14, // 39: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	16, // 40: product.ProductService.GetProductReviews:output_type -> product.GetProductReviewsResponse
	35, // [35:41] is the sub-list for method output_type
	29, // [29:35] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		EnumInfos:         file_proto_product_product_proto_enumTypes,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
