logger:
  format: text
  level: info
  path: "./logs/example.log" # empty string means stdout

nats:
  url: "nats://localhost:4222"

deployer:
  nodes:
    - name: rng-01
      type: rng
      config:
        low: -100
        high: 100
        interval: 1.0
    
    - name: sum-01
      type: sum
      subscriptions:
        - rng-01
      config:
        init_sum: 0
        upper_limit: 1000
        lower_limit: -1000
