app:
  host: localhost
  port: 8080

eventbus:
  url: nats://localhost:4222

node:
  name: rng
  type: rng
  emit: 
    - on_tick: on.rng.random
  rpc:
    - req_metadata: rpc.rng.metadata
    - req_parameters: rpc.rng.parameters
    - req_status: rpc.rng.status
    - req_random: rpc.rng.random
  params:
    min: 0
    max: 100
    seed: 1234567890
    interval: 1
