app:
  host: localhost
  port: 8080

eventbus:
  url: nats://localhost:4222

node:
  name: rng
  type: rng
  emit: 
    - on_tick: on.rng.random
  rpc:
    - get_config: rpc.rng.config
    - get_status: rpc.rng.status
    - get_metadata: rpc.rng.metadata
  params:
    min: 0
    max: 100
    seed: 1234567890
    interval: 1
