name: sum
type: sum
on: 
  on_random: on.rng.random
rpc:
  req_metadata: rpc.sum.metadata
  req_status: rpc.sum.status
  req_parameters: rpc.sum.parameters
  req_sum: rpc.sum.sum
params:
  init_sum: 0
  upper_limit: 500
  lower_limit: -500
