app:
  host: localhost
  port: 8081

eventbus:
  url: nats://localhost:4222

node:
  name: sum
  type: sum
  on: 
    - on_random: on.sum.random
  rpc:
    - get_config: rpc.sum.config
    - get_status: rpc.sum.status
    - get_metadata: rpc.sum.metadata
    - get_sum: rpc.sum.sum
  params:
    init_sum: 0
    upper_limit: 500
    lower_limit: -500
