nats:
  url: nats://localhost:4222

deployer:
  nodes:
    - name: sum_positive
      type: sum
      subscriptions: 
        - rng_positive
      config:
        init_sum: 0
        upper_limit: 500
        lower_limit: 0
    - name: sum_negative
      type: sum
      subscriptions: 
        - rng_negative
      config:
        init_sum: 0
        upper_limit: 0
        lower_limit: -500
    - name: sum_all
      type: sum
      subscriptions: 
        - rng_positive
        - rng_negative
      config:
        init_sum: 0
        upper_limit: 500
        lower_limit: -500
