name: binancetrade
type: trade
emit: 
  emit_trade: on.binance.trade
rpc:
  req_metadata: rpc.binancetrade.metadata
  req_parameters: rpc.binancetrade.parameters
  req_status: rpc.binancetrade.status
params:
  exchange: binance
  instrument: SPOT
  symbol: BTC-USDT
