name: binance.btc.usdt.trade
type: trade
emit: 
  emit_trade: on.binance.btc.usdt.trade
rpc:
  req_metadata: rpc.binance.btc.usdt.trade.metadata
  req_parameters: rpc.binance.btc.usdt.trade.parameters
  req_status: rpc.binance.btc.usdt.trade.status
params:
  exchange: binance
  instrument: spot
  symbol: BTC-USDT
