services:
  nats:
    image: nats:2.11-alpine
    container_name: sequex-nats
    ports:
      - "4222:4222"   # NATS client port
      - "8222:8222"   # HTTP monitoring port
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--http_port=8222"
      - "--port=4222"
    volumes:
      - nats_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
volumes:
  nats_data:
    driver: local
  redis_data:
    driver: local
