// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: app/order.proto

package order

import (
	shared "github.com/BullionBear/sequex/internal/model/protobuf/common/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status enum
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_PENDING   OrderStatus = 0
	OrderStatus_ORDER_STATUS_FILLED    OrderStatus = 1
	OrderStatus_ORDER_STATUS_CANCELLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_REJECTED  OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_PENDING",
		1: "ORDER_STATUS_FILLED",
		2: "ORDER_STATUS_CANCELLED",
		3: "ORDER_STATUS_REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_PENDING":   0,
		"ORDER_STATUS_FILLED":    1,
		"ORDER_STATUS_CANCELLED": 2,
		"ORDER_STATUS_REJECTED":  3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_app_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_app_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_app_order_proto_rawDescGZIP(), []int{0}
}

type TradeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Qty           float64                `protobuf:"fixed64,3,opt,name=qty,proto3" json:"qty,omitempty"`
	QuoteQty      float64                `protobuf:"fixed64,4,opt,name=quote_qty,json=quoteQty,proto3" json:"quote_qty,omitempty"`
	Time          int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Side          shared.OrderSide       `protobuf:"varint,6,opt,name=side,proto3,enum=shared.OrderSide" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeMessage) Reset() {
	*x = TradeMessage{}
	mi := &file_app_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeMessage) ProtoMessage() {}

func (x *TradeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeMessage.ProtoReflect.Descriptor instead.
func (*TradeMessage) Descriptor() ([]byte, []int) {
	return file_app_order_proto_rawDescGZIP(), []int{0}
}

func (x *TradeMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TradeMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeMessage) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *TradeMessage) GetQuoteQty() float64 {
	if x != nil {
		return x.QuoteQty
	}
	return 0
}

func (x *TradeMessage) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TradeMessage) GetSide() shared.OrderSide {
	if x != nil {
		return x.Side
	}
	return shared.OrderSide(0)
}

// Order message that uses shared types
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side          shared.OrderSide       `protobuf:"varint,5,opt,name=side,proto3,enum=shared.OrderSide" json:"side,omitempty"`
	User          *shared.UserInfo       `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_app_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_app_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetSide() shared.OrderSide {
	if x != nil {
		return x.Side
	}
	return shared.OrderSide(0)
}

func (x *Order) GetUser() *shared.UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Order response message
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_app_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_app_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_PENDING
}

func (x *OrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrderResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_app_order_proto protoreflect.FileDescriptor

const file_app_order_proto_rawDesc = "" +
	"\n" +
	"\x0fapp/order.proto\x12\x05order\x1a\x13common/shared.proto\"\x9e\x01\n" +
	"\fTradeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x01R\x03qty\x12\x1b\n" +
	"\tquote_qty\x18\x04 \x01(\x01R\bquoteQty\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\x12%\n" +
	"\x04side\x18\x06 \x01(\x0e2\x11.shared.OrderSideR\x04side\"\xd7\x01\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12%\n" +
	"\x04side\x18\x05 \x01(\x0e2\x11.shared.OrderSideR\x04side\x12$\n" +
	"\x04user\x18\x06 \x01(\v2\x10.shared.UserInfoR\x04user\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\x8e\x01\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp*w\n" +
	"\vOrderStatus\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x00\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x03BGZEgithub.com/BullionBear/sequex/internal/model/protobuf/app/order;orderb\x06proto3"

var (
	file_app_order_proto_rawDescOnce sync.Once
	file_app_order_proto_rawDescData []byte
)

func file_app_order_proto_rawDescGZIP() []byte {
	file_app_order_proto_rawDescOnce.Do(func() {
		file_app_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_order_proto_rawDesc), len(file_app_order_proto_rawDesc)))
	})
	return file_app_order_proto_rawDescData
}

var file_app_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_order_proto_goTypes = []any{
	(OrderStatus)(0),        // 0: order.OrderStatus
	(*TradeMessage)(nil),    // 1: order.TradeMessage
	(*Order)(nil),           // 2: order.Order
	(*OrderResponse)(nil),   // 3: order.OrderResponse
	(shared.OrderSide)(0),   // 4: shared.OrderSide
	(*shared.UserInfo)(nil), // 5: shared.UserInfo
}
var file_app_order_proto_depIdxs = []int32{
	4, // 0: order.TradeMessage.side:type_name -> shared.OrderSide
	4, // 1: order.Order.side:type_name -> shared.OrderSide
	5, // 2: order.Order.user:type_name -> shared.UserInfo
	0, // 3: order.OrderResponse.status:type_name -> order.OrderStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_order_proto_init() }
func file_app_order_proto_init() {
	if File_app_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_order_proto_rawDesc), len(file_app_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_order_proto_goTypes,
		DependencyIndexes: file_app_order_proto_depIdxs,
		EnumInfos:         file_app_order_proto_enumTypes,
		MessageInfos:      file_app_order_proto_msgTypes,
	}.Build()
	File_app_order_proto = out.File
	file_app_order_proto_goTypes = nil
	file_app_order_proto_depIdxs = nil
}
