// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: protobuf/app/trade.proto

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange      Exchange               `protobuf:"varint,2,opt,name=exchange,proto3,enum=app.Exchange" json:"exchange,omitempty"`
	Instrument    Instrument             `protobuf:"varint,3,opt,name=instrument,proto3,enum=app.Instrument" json:"instrument,omitempty"`
	Symbol        *Symbol                `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,5,opt,name=side,proto3,enum=app.Side" json:"side,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_protobuf_app_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_app_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_protobuf_app_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetExchange() Exchange {
	if x != nil {
		return x.Exchange
	}
	return Exchange_EXCHANGE_UNSPECIFIED
}

func (x *Trade) GetInstrument() Instrument {
	if x != nil {
		return x.Instrument
	}
	return Instrument_INSTRUMENT_UNSPECIFIED
}

func (x *Trade) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *Trade) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *Symbol                `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Instrument    Instrument             `protobuf:"varint,2,opt,name=instrument,proto3,enum=app.Instrument" json:"instrument,omitempty"`
	Exchange      Exchange               `protobuf:"varint,3,opt,name=exchange,proto3,enum=app.Exchange" json:"exchange,omitempty"`
	StartSeq      int64                  `protobuf:"varint,4,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"`
	EndSeq        int64                  `protobuf:"varint,5,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`
	NextSeq       int64                  `protobuf:"varint,6,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Open          float64                `protobuf:"fixed64,9,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,10,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,11,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,12,opt,name=close,proto3" json:"close,omitempty"`
	Mean          float64                `protobuf:"fixed64,13,opt,name=mean,proto3" json:"mean,omitempty"`
	Std           float64                `protobuf:"fixed64,14,opt,name=std,proto3" json:"std,omitempty"`
	Median        float64                `protobuf:"fixed64,15,opt,name=median,proto3" json:"median,omitempty"`
	FirstQuartile float64                `protobuf:"fixed64,16,opt,name=first_quartile,json=firstQuartile,proto3" json:"first_quartile,omitempty"`
	ThirdQuartile float64                `protobuf:"fixed64,17,opt,name=third_quartile,json=thirdQuartile,proto3" json:"third_quartile,omitempty"`
	VolumeBase    float64                `protobuf:"fixed64,18,opt,name=volume_base,json=volumeBase,proto3" json:"volume_base,omitempty"`
	VolumeQuote   float64                `protobuf:"fixed64,19,opt,name=volume_quote,json=volumeQuote,proto3" json:"volume_quote,omitempty"`
	Count         int64                  `protobuf:"varint,20,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_protobuf_app_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_app_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_protobuf_app_trade_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *Bar) GetInstrument() Instrument {
	if x != nil {
		return x.Instrument
	}
	return Instrument_INSTRUMENT_UNSPECIFIED
}

func (x *Bar) GetExchange() Exchange {
	if x != nil {
		return x.Exchange
	}
	return Exchange_EXCHANGE_UNSPECIFIED
}

func (x *Bar) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *Bar) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

func (x *Bar) GetNextSeq() int64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *Bar) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Bar) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Bar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Bar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Bar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Bar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Bar) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *Bar) GetStd() float64 {
	if x != nil {
		return x.Std
	}
	return 0
}

func (x *Bar) GetMedian() float64 {
	if x != nil {
		return x.Median
	}
	return 0
}

func (x *Bar) GetFirstQuartile() float64 {
	if x != nil {
		return x.FirstQuartile
	}
	return 0
}

func (x *Bar) GetThirdQuartile() float64 {
	if x != nil {
		return x.ThirdQuartile
	}
	return 0
}

func (x *Bar) GetVolumeBase() float64 {
	if x != nil {
		return x.VolumeBase
	}
	return 0
}

func (x *Bar) GetVolumeQuote() float64 {
	if x != nil {
		return x.VolumeQuote
	}
	return 0
}

func (x *Bar) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_protobuf_app_trade_proto protoreflect.FileDescriptor

const file_protobuf_app_trade_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/app/trade.proto\x12\x03app\x1a\x19protobuf/app/shared.proto\"\x87\x02\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\bexchange\x18\x02 \x01(\x0e2\r.app.ExchangeR\bexchange\x12/\n" +
	"\n" +
	"instrument\x18\x03 \x01(\x0e2\x0f.app.InstrumentR\n" +
	"instrument\x12#\n" +
	"\x06symbol\x18\x04 \x01(\v2\v.app.SymbolR\x06symbol\x12\x1d\n" +
	"\x04side\x18\x05 \x01(\x0e2\t.app.SideR\x04side\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x01R\bquantity\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\xc7\x04\n" +
	"\x03Bar\x12#\n" +
	"\x06symbol\x18\x01 \x01(\v2\v.app.SymbolR\x06symbol\x12/\n" +
	"\n" +
	"instrument\x18\x02 \x01(\x0e2\x0f.app.InstrumentR\n" +
	"instrument\x12)\n" +
	"\bexchange\x18\x03 \x01(\x0e2\r.app.ExchangeR\bexchange\x12\x1b\n" +
	"\tstart_seq\x18\x04 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x05 \x01(\x03R\x06endSeq\x12\x19\n" +
	"\bnext_seq\x18\x06 \x01(\x03R\anextSeq\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x12\x12\n" +
	"\x04open\x18\t \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\n" +
	" \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\v \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\f \x01(\x01R\x05close\x12\x12\n" +
	"\x04mean\x18\r \x01(\x01R\x04mean\x12\x10\n" +
	"\x03std\x18\x0e \x01(\x01R\x03std\x12\x16\n" +
	"\x06median\x18\x0f \x01(\x01R\x06median\x12%\n" +
	"\x0efirst_quartile\x18\x10 \x01(\x01R\rfirstQuartile\x12%\n" +
	"\x0ethird_quartile\x18\x11 \x01(\x01R\rthirdQuartile\x12\x1f\n" +
	"\vvolume_base\x18\x12 \x01(\x01R\n" +
	"volumeBase\x12!\n" +
	"\fvolume_quote\x18\x13 \x01(\x01R\vvolumeQuote\x12\x14\n" +
	"\x05count\x18\x14 \x01(\x03R\x05countB;Z9github.com/BullionBear/sequex/internal/model/protobuf/appb\x06proto3"

var (
	file_protobuf_app_trade_proto_rawDescOnce sync.Once
	file_protobuf_app_trade_proto_rawDescData []byte
)

func file_protobuf_app_trade_proto_rawDescGZIP() []byte {
	file_protobuf_app_trade_proto_rawDescOnce.Do(func() {
		file_protobuf_app_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_app_trade_proto_rawDesc), len(file_protobuf_app_trade_proto_rawDesc)))
	})
	return file_protobuf_app_trade_proto_rawDescData
}

var file_protobuf_app_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_app_trade_proto_goTypes = []any{
	(*Trade)(nil),   // 0: app.Trade
	(*Bar)(nil),     // 1: app.Bar
	(Exchange)(0),   // 2: app.Exchange
	(Instrument)(0), // 3: app.Instrument
	(*Symbol)(nil),  // 4: app.Symbol
	(Side)(0),       // 5: app.Side
}
var file_protobuf_app_trade_proto_depIdxs = []int32{
	2, // 0: app.Trade.exchange:type_name -> app.Exchange
	3, // 1: app.Trade.instrument:type_name -> app.Instrument
	4, // 2: app.Trade.symbol:type_name -> app.Symbol
	5, // 3: app.Trade.side:type_name -> app.Side
	4, // 4: app.Bar.symbol:type_name -> app.Symbol
	3, // 5: app.Bar.instrument:type_name -> app.Instrument
	2, // 6: app.Bar.exchange:type_name -> app.Exchange
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_app_trade_proto_init() }
func file_protobuf_app_trade_proto_init() {
	if File_protobuf_app_trade_proto != nil {
		return
	}
	file_protobuf_app_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_app_trade_proto_rawDesc), len(file_protobuf_app_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_app_trade_proto_goTypes,
		DependencyIndexes: file_protobuf_app_trade_proto_depIdxs,
		MessageInfos:      file_protobuf_app_trade_proto_msgTypes,
	}.Build()
	File_protobuf_app_trade_proto = out.File
	file_protobuf_app_trade_proto_goTypes = nil
	file_protobuf_app_trade_proto_depIdxs = nil
}
