// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: protobuf/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_OK                    ErrorCode = 0
	ErrorCode_ERROR_CODE_UNSPECIFIED           ErrorCode = 1
	ErrorCode_ERROR_CODE_DESERIALIZATION_ERROR ErrorCode = 2
	ErrorCode_ERROR_CODE_SERIALIZATION_ERROR   ErrorCode = 3
	ErrorCode_ERROR_CODE_INVALID_REQUEST       ErrorCode = 4
	ErrorCode_ERROR_CODE_UNAUTHORIZED          ErrorCode = 5
	ErrorCode_ERROR_CODE_FORBIDDEN             ErrorCode = 6
	ErrorCode_ERROR_CODE_INTERNAL_SERVER_ERROR ErrorCode = 7
	ErrorCode_ERROR_CODE_NOT_FOUND             ErrorCode = 8
	ErrorCode_ERROR_CODE_CONFLICT              ErrorCode = 9
	ErrorCode_ERROR_CODE_BAD_REQUEST           ErrorCode = 10
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_OK",
		1:  "ERROR_CODE_UNSPECIFIED",
		2:  "ERROR_CODE_DESERIALIZATION_ERROR",
		3:  "ERROR_CODE_SERIALIZATION_ERROR",
		4:  "ERROR_CODE_INVALID_REQUEST",
		5:  "ERROR_CODE_UNAUTHORIZED",
		6:  "ERROR_CODE_FORBIDDEN",
		7:  "ERROR_CODE_INTERNAL_SERVER_ERROR",
		8:  "ERROR_CODE_NOT_FOUND",
		9:  "ERROR_CODE_CONFLICT",
		10: "ERROR_CODE_BAD_REQUEST",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_OK":                    0,
		"ERROR_CODE_UNSPECIFIED":           1,
		"ERROR_CODE_DESERIALIZATION_ERROR": 2,
		"ERROR_CODE_SERIALIZATION_ERROR":   3,
		"ERROR_CODE_INVALID_REQUEST":       4,
		"ERROR_CODE_UNAUTHORIZED":          5,
		"ERROR_CODE_FORBIDDEN":             6,
		"ERROR_CODE_INTERNAL_SERVER_ERROR": 7,
		"ERROR_CODE_NOT_FOUND":             8,
		"ERROR_CODE_CONFLICT":              9,
		"ERROR_CODE_BAD_REQUEST":           10,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_common_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_protobuf_common_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{0}
}

type ParametersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParametersRequest) Reset() {
	*x = ParametersRequest{}
	mi := &file_protobuf_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametersRequest) ProtoMessage() {}

func (x *ParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametersRequest.ProtoReflect.Descriptor instead.
func (*ParametersRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *ParametersRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ParametersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Parameters    []byte                 `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParametersResponse) Reset() {
	*x = ParametersResponse{}
	mi := &file_protobuf_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParametersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametersResponse) ProtoMessage() {}

func (x *ParametersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametersResponse.ProtoReflect.Descriptor instead.
func (*ParametersResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *ParametersResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParametersResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_OK
}

func (x *ParametersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParametersResponse) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_protobuf_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status        []byte                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_protobuf_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_OK
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_protobuf_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *MetadataRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          ErrorCode              `protobuf:"varint,2,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Emit          map[string]string      `protobuf:"bytes,6,rep,name=emit,proto3" json:"emit,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	On            map[string]string      `protobuf:"bytes,7,rep,name=on,proto3" json:"on,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Rpc           map[string]string      `protobuf:"bytes,8,rep,name=rpc,proto3" json:"rpc,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_protobuf_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *MetadataResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MetadataResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_OK
}

func (x *MetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MetadataResponse) GetEmit() map[string]string {
	if x != nil {
		return x.Emit
	}
	return nil
}

func (x *MetadataResponse) GetOn() map[string]string {
	if x != nil {
		return x.On
	}
	return nil
}

func (x *MetadataResponse) GetRpc() map[string]string {
	if x != nil {
		return x.Rpc
	}
	return nil
}

var File_protobuf_common_common_proto protoreflect.FileDescriptor

const file_protobuf_common_common_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/common/common.proto\x12\x06common\"#\n" +
	"\x11ParametersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x85\x01\n" +
	"\x12ParametersResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x04code\x18\x02 \x01(\x0e2\x11.common.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"parameters\x18\x04 \x01(\fR\n" +
	"parameters\"\x1f\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"y\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x04code\x18\x02 \x01(\x0e2\x11.common.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\fR\x06status\"!\n" +
	"\x0fMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xdd\x03\n" +
	"\x10MetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x04code\x18\x02 \x01(\x0e2\x11.common.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x126\n" +
	"\x04emit\x18\x06 \x03(\v2\".common.MetadataResponse.EmitEntryR\x04emit\x120\n" +
	"\x02on\x18\a \x03(\v2 .common.MetadataResponse.OnEntryR\x02on\x123\n" +
	"\x03rpc\x18\b \x03(\v2!.common.MetadataResponse.RpcEntryR\x03rpc\x1a7\n" +
	"\tEmitEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a5\n" +
	"\aOnEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bRpcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd0\x02\n" +
	"\tErrorCode\x12\x11\n" +
	"\rERROR_CODE_OK\x10\x00\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x01\x12$\n" +
	" ERROR_CODE_DESERIALIZATION_ERROR\x10\x02\x12\"\n" +
	"\x1eERROR_CODE_SERIALIZATION_ERROR\x10\x03\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x04\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x05\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x06\x12$\n" +
	" ERROR_CODE_INTERNAL_SERVER_ERROR\x10\a\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\b\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\t\x12\x1a\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\n" +
	"B>Z<github.com/BullionBear/sequex/internal/model/protobuf/commonb\x06proto3"

var (
	file_protobuf_common_common_proto_rawDescOnce sync.Once
	file_protobuf_common_common_proto_rawDescData []byte
)

func file_protobuf_common_common_proto_rawDescGZIP() []byte {
	file_protobuf_common_common_proto_rawDescOnce.Do(func() {
		file_protobuf_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_common_common_proto_rawDesc), len(file_protobuf_common_common_proto_rawDesc)))
	})
	return file_protobuf_common_common_proto_rawDescData
}

var file_protobuf_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protobuf_common_common_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: common.ErrorCode
	(*ParametersRequest)(nil),  // 1: common.ParametersRequest
	(*ParametersResponse)(nil), // 2: common.ParametersResponse
	(*StatusRequest)(nil),      // 3: common.StatusRequest
	(*StatusResponse)(nil),     // 4: common.StatusResponse
	(*MetadataRequest)(nil),    // 5: common.MetadataRequest
	(*MetadataResponse)(nil),   // 6: common.MetadataResponse
	nil,                        // 7: common.MetadataResponse.EmitEntry
	nil,                        // 8: common.MetadataResponse.OnEntry
	nil,                        // 9: common.MetadataResponse.RpcEntry
}
var file_protobuf_common_common_proto_depIdxs = []int32{
	0, // 0: common.ParametersResponse.code:type_name -> common.ErrorCode
	0, // 1: common.StatusResponse.code:type_name -> common.ErrorCode
	0, // 2: common.MetadataResponse.code:type_name -> common.ErrorCode
	7, // 3: common.MetadataResponse.emit:type_name -> common.MetadataResponse.EmitEntry
	8, // 4: common.MetadataResponse.on:type_name -> common.MetadataResponse.OnEntry
	9, // 5: common.MetadataResponse.rpc:type_name -> common.MetadataResponse.RpcEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_common_common_proto_init() }
func file_protobuf_common_common_proto_init() {
	if File_protobuf_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_common_common_proto_rawDesc), len(file_protobuf_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_common_common_proto_goTypes,
		DependencyIndexes: file_protobuf_common_common_proto_depIdxs,
		EnumInfos:         file_protobuf_common_common_proto_enumTypes,
		MessageInfos:      file_protobuf_common_common_proto_msgTypes,
	}.Build()
	File_protobuf_common_common_proto = out.File
	file_protobuf_common_common_proto_goTypes = nil
	file_protobuf_common_common_proto_depIdxs = nil
}
