// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: example/rng.proto

package rng

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RngMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Random        int64                  `protobuf:"varint,1,opt,name=random,proto3" json:"random,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RngMessage) Reset() {
	*x = RngMessage{}
	mi := &file_example_rng_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RngMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RngMessage) ProtoMessage() {}

func (x *RngMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_rng_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RngMessage.ProtoReflect.Descriptor instead.
func (*RngMessage) Descriptor() ([]byte, []int) {
	return file_example_rng_proto_rawDescGZIP(), []int{0}
}

func (x *RngMessage) GetRandom() int64 {
	if x != nil {
		return x.Random
	}
	return 0
}

type RngCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RngCountRequest) Reset() {
	*x = RngCountRequest{}
	mi := &file_example_rng_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RngCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RngCountRequest) ProtoMessage() {}

func (x *RngCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_rng_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RngCountRequest.ProtoReflect.Descriptor instead.
func (*RngCountRequest) Descriptor() ([]byte, []int) {
	return file_example_rng_proto_rawDescGZIP(), []int{1}
}

type RngCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NSuccess      int64                  `protobuf:"varint,1,opt,name=n_success,json=nSuccess,proto3" json:"n_success,omitempty"`
	NFailure      int64                  `protobuf:"varint,2,opt,name=n_failure,json=nFailure,proto3" json:"n_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RngCountResponse) Reset() {
	*x = RngCountResponse{}
	mi := &file_example_rng_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RngCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RngCountResponse) ProtoMessage() {}

func (x *RngCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_rng_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RngCountResponse.ProtoReflect.Descriptor instead.
func (*RngCountResponse) Descriptor() ([]byte, []int) {
	return file_example_rng_proto_rawDescGZIP(), []int{2}
}

func (x *RngCountResponse) GetNSuccess() int64 {
	if x != nil {
		return x.NSuccess
	}
	return 0
}

func (x *RngCountResponse) GetNFailure() int64 {
	if x != nil {
		return x.NFailure
	}
	return 0
}

var File_example_rng_proto protoreflect.FileDescriptor

const file_example_rng_proto_rawDesc = "" +
	"\n" +
	"\x11example/rng.proto\x12\x03rng\"$\n" +
	"\n" +
	"RngMessage\x12\x16\n" +
	"\x06random\x18\x01 \x01(\x03R\x06random\"\x11\n" +
	"\x0fRngCountRequest\"L\n" +
	"\x10RngCountResponse\x12\x1b\n" +
	"\tn_success\x18\x01 \x01(\x03R\bnSuccess\x12\x1b\n" +
	"\tn_failure\x18\x02 \x01(\x03R\bnFailureBCZAgithub.com/BullionBear/sequex/internal/model/protobuf/example/rngb\x06proto3"

var (
	file_example_rng_proto_rawDescOnce sync.Once
	file_example_rng_proto_rawDescData []byte
)

func file_example_rng_proto_rawDescGZIP() []byte {
	file_example_rng_proto_rawDescOnce.Do(func() {
		file_example_rng_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_rng_proto_rawDesc), len(file_example_rng_proto_rawDesc)))
	})
	return file_example_rng_proto_rawDescData
}

var file_example_rng_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_rng_proto_goTypes = []any{
	(*RngMessage)(nil),       // 0: rng.RngMessage
	(*RngCountRequest)(nil),  // 1: rng.RngCountRequest
	(*RngCountResponse)(nil), // 2: rng.RngCountResponse
}
var file_example_rng_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_rng_proto_init() }
func file_example_rng_proto_init() {
	if File_example_rng_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_rng_proto_rawDesc), len(file_example_rng_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_rng_proto_goTypes,
		DependencyIndexes: file_example_rng_proto_depIdxs,
		MessageInfos:      file_example_rng_proto_msgTypes,
	}.Build()
	File_example_rng_proto = out.File
	file_example_rng_proto_goTypes = nil
	file_example_rng_proto_depIdxs = nil
}
