accounts:
  binance:
    - name: "account1"
      api_key: "your_api_key_here"
      api_secret: "your_api_secret_here"
    - name: "account2"
      api_key: "your_api_key_here"
      api_secret: "your_api_secret_here"
  binanceperp:
    - name: "account1"
      api_key: "your_api_key_here"
      api_secret: "your_api_secret_here"
    - name: "account2"
      api_key: "your_api_key_here"
      api_secret: "your_api_secret_here"

market:
  binance:
    - "BTCUSDT"
    - "ETHUSDT"
  binanceperp:
    - "BTCUSDT"
    - "ETHUSDT"