logger:
  format: text
  level: info
  path: logs/example.log

nats:
  url: "nats://localhost:4222"

deployer:
  nodes:
    - name: rng-01
      type: rng
      config:
        low: -100
        high: 100
        interval: 1.0
      subscriptions:
        - sum-01
    
    - name: sum-01
      type: sum
      config:
        init_sum: 0
        upper_limit: 1000
        lower_limit: -1000
