nats:
  url: nats://localhost:4222

deployer:
  nodes:
    rng_positive:
      type: rng
      subscriptions: []
      config:
        low: 1
        high: 100
        interval: 1
    rng_negative:
      type: rng
      subscriptions: []
      config:
        low: -100
        high: -1
        interval: 1
