// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: proto/solvexity.proto

package solvexity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Solvexity_Solve_FullMethodName = "/solvexity.Solvexity/Solve"
)

// SolvexityClient is the client API for Solvexity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolvexityClient interface {
	Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
}

type solvexityClient struct {
	cc grpc.ClientConnInterface
}

func NewSolvexityClient(cc grpc.ClientConnInterface) SolvexityClient {
	return &solvexityClient{cc}
}

func (c *solvexityClient) Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, Solvexity_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolvexityServer is the server API for Solvexity service.
// All implementations must embed UnimplementedSolvexityServer
// for forward compatibility
type SolvexityServer interface {
	Solve(context.Context, *SolveRequest) (*SolveResponse, error)
	mustEmbedUnimplementedSolvexityServer()
}

// UnimplementedSolvexityServer must be embedded to have forward compatible implementations.
type UnimplementedSolvexityServer struct {
}

func (UnimplementedSolvexityServer) Solve(context.Context, *SolveRequest) (*SolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSolvexityServer) mustEmbedUnimplementedSolvexityServer() {}

// UnsafeSolvexityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolvexityServer will
// result in compilation errors.
type UnsafeSolvexityServer interface {
	mustEmbedUnimplementedSolvexityServer()
}

func RegisterSolvexityServer(s grpc.ServiceRegistrar, srv SolvexityServer) {
	s.RegisterService(&Solvexity_ServiceDesc, srv)
}

func _Solvexity_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolvexityServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Solvexity_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolvexityServer).Solve(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Solvexity_ServiceDesc is the grpc.ServiceDesc for Solvexity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Solvexity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solvexity.Solvexity",
	HandlerType: (*SolvexityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _Solvexity_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/solvexity.proto",
}
