// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/shared.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Instrument int32

const (
	Instrument_INSTRUMENT_UNSPECIFIED Instrument = 0
	Instrument_INSTRUMENT_SPOT        Instrument = 1
	Instrument_INSTRUMENT_MARGIN      Instrument = 2
	Instrument_INSTRUMENT_PERP        Instrument = 3
	Instrument_INSTRUMENT_INVERSE     Instrument = 4
	Instrument_INSTRUMENT_FUTURES     Instrument = 5
	Instrument_INSTRUMENT_OPTION      Instrument = 6
)

// Enum value maps for Instrument.
var (
	Instrument_name = map[int32]string{
		0: "INSTRUMENT_UNSPECIFIED",
		1: "INSTRUMENT_SPOT",
		2: "INSTRUMENT_MARGIN",
		3: "INSTRUMENT_PERP",
		4: "INSTRUMENT_INVERSE",
		5: "INSTRUMENT_FUTURES",
		6: "INSTRUMENT_OPTION",
	}
	Instrument_value = map[string]int32{
		"INSTRUMENT_UNSPECIFIED": 0,
		"INSTRUMENT_SPOT":        1,
		"INSTRUMENT_MARGIN":      2,
		"INSTRUMENT_PERP":        3,
		"INSTRUMENT_INVERSE":     4,
		"INSTRUMENT_FUTURES":     5,
		"INSTRUMENT_OPTION":      6,
	}
)

func (x Instrument) Enum() *Instrument {
	p := new(Instrument)
	*p = x
	return p
}

func (x Instrument) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instrument) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_shared_proto_enumTypes[0].Descriptor()
}

func (Instrument) Type() protoreflect.EnumType {
	return &file_protobuf_shared_proto_enumTypes[0]
}

func (x Instrument) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instrument.Descriptor instead.
func (Instrument) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_shared_proto_rawDescGZIP(), []int{0}
}

type Exchange int32

const (
	Exchange_EXCHANGE_UNSPECIFIED  Exchange = 0
	Exchange_EXCHANGE_BINANCE      Exchange = 1
	Exchange_EXCHANGE_BINANCE_PERP Exchange = 2
	Exchange_EXCHANGE_BYBIT        Exchange = 3
)

// Enum value maps for Exchange.
var (
	Exchange_name = map[int32]string{
		0: "EXCHANGE_UNSPECIFIED",
		1: "EXCHANGE_BINANCE",
		2: "EXCHANGE_BINANCE_PERP",
		3: "EXCHANGE_BYBIT",
	}
	Exchange_value = map[string]int32{
		"EXCHANGE_UNSPECIFIED":  0,
		"EXCHANGE_BINANCE":      1,
		"EXCHANGE_BINANCE_PERP": 2,
		"EXCHANGE_BYBIT":        3,
	}
)

func (x Exchange) Enum() *Exchange {
	p := new(Exchange)
	*p = x
	return p
}

func (x Exchange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exchange) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_shared_proto_enumTypes[1].Descriptor()
}

func (Exchange) Type() protoreflect.EnumType {
	return &file_protobuf_shared_proto_enumTypes[1]
}

func (x Exchange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exchange.Descriptor instead.
func (Exchange) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_shared_proto_rawDescGZIP(), []int{1}
}

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_shared_proto_enumTypes[2].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_protobuf_shared_proto_enumTypes[2]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_shared_proto_rawDescGZIP(), []int{2}
}

type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_shared_proto_enumTypes[3].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_protobuf_shared_proto_enumTypes[3]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_shared_proto_rawDescGZIP(), []int{3}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
	OrderType_ORDER_TYPE_STOP_MARKET OrderType = 3
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
		3: "ORDER_TYPE_STOP_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
		"ORDER_TYPE_STOP_MARKET": 3,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_shared_proto_enumTypes[4].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_protobuf_shared_proto_enumTypes[4]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_shared_proto_rawDescGZIP(), []int{4}
}

type Symbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_protobuf_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_protobuf_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Symbol) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Symbol) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

var File_protobuf_shared_proto protoreflect.FileDescriptor

const file_protobuf_shared_proto_rawDesc = "" +
	"\n" +
	"\x15protobuf/shared.proto\x12\x03app\"2\n" +
	"\x06Symbol\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote*\xb0\x01\n" +
	"\n" +
	"Instrument\x12\x1a\n" +
	"\x16INSTRUMENT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fINSTRUMENT_SPOT\x10\x01\x12\x15\n" +
	"\x11INSTRUMENT_MARGIN\x10\x02\x12\x13\n" +
	"\x0fINSTRUMENT_PERP\x10\x03\x12\x16\n" +
	"\x12INSTRUMENT_INVERSE\x10\x04\x12\x16\n" +
	"\x12INSTRUMENT_FUTURES\x10\x05\x12\x15\n" +
	"\x11INSTRUMENT_OPTION\x10\x06*i\n" +
	"\bExchange\x12\x18\n" +
	"\x14EXCHANGE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EXCHANGE_BINANCE\x10\x01\x12\x19\n" +
	"\x15EXCHANGE_BINANCE_PERP\x10\x02\x12\x12\n" +
	"\x0eEXCHANGE_BYBIT\x10\x03*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*q\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x03*p\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02\x12\x1a\n" +
	"\x16ORDER_TYPE_STOP_MARKET\x10\x03B7Z5github.com/BullionBear/sequex/internal/model/protobufb\x06proto3"

var (
	file_protobuf_shared_proto_rawDescOnce sync.Once
	file_protobuf_shared_proto_rawDescData []byte
)

func file_protobuf_shared_proto_rawDescGZIP() []byte {
	file_protobuf_shared_proto_rawDescOnce.Do(func() {
		file_protobuf_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_shared_proto_rawDesc), len(file_protobuf_shared_proto_rawDesc)))
	})
	return file_protobuf_shared_proto_rawDescData
}

var file_protobuf_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_protobuf_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_shared_proto_goTypes = []any{
	(Instrument)(0),  // 0: app.Instrument
	(Exchange)(0),    // 1: app.Exchange
	(Side)(0),        // 2: app.Side
	(TimeInForce)(0), // 3: app.TimeInForce
	(OrderType)(0),   // 4: app.OrderType
	(*Symbol)(nil),   // 5: app.Symbol
}
var file_protobuf_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_shared_proto_init() }
func file_protobuf_shared_proto_init() {
	if File_protobuf_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_shared_proto_rawDesc), len(file_protobuf_shared_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_shared_proto_goTypes,
		DependencyIndexes: file_protobuf_shared_proto_depIdxs,
		EnumInfos:         file_protobuf_shared_proto_enumTypes,
		MessageInfos:      file_protobuf_shared_proto_msgTypes,
	}.Build()
	File_protobuf_shared_proto = out.File
	file_protobuf_shared_proto_goTypes = nil
	file_protobuf_shared_proto_depIdxs = nil
}
