// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: protobuf/trade.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange      Exchange               `protobuf:"varint,2,opt,name=exchange,proto3,enum=app.Exchange" json:"exchange,omitempty"`
	Instrument    Instrument             `protobuf:"varint,3,opt,name=instrument,proto3,enum=app.Instrument" json:"instrument,omitempty"`
	Symbol        *Symbol                `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,5,opt,name=side,proto3,enum=app.Side" json:"side,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_protobuf_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_protobuf_trade_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetExchange() Exchange {
	if x != nil {
		return x.Exchange
	}
	return Exchange_EXCHANGE_UNSPECIFIED
}

func (x *Trade) GetInstrument() Instrument {
	if x != nil {
		return x.Instrument
	}
	return Instrument_INSTRUMENT_UNSPECIFIED
}

func (x *Trade) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *Trade) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_protobuf_trade_proto protoreflect.FileDescriptor

const file_protobuf_trade_proto_rawDesc = "" +
	"\n" +
	"\x14protobuf/trade.proto\x12\x03app\x1a\x15protobuf/shared.proto\"\x87\x02\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12)\n" +
	"\bexchange\x18\x02 \x01(\x0e2\r.app.ExchangeR\bexchange\x12/\n" +
	"\n" +
	"instrument\x18\x03 \x01(\x0e2\x0f.app.InstrumentR\n" +
	"instrument\x12#\n" +
	"\x06symbol\x18\x04 \x01(\v2\v.app.SymbolR\x06symbol\x12\x1d\n" +
	"\x04side\x18\x05 \x01(\x0e2\t.app.SideR\x04side\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x01R\bquantity\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestampB7Z5github.com/BullionBear/sequex/internal/model/protobufb\x06proto3"

var (
	file_protobuf_trade_proto_rawDescOnce sync.Once
	file_protobuf_trade_proto_rawDescData []byte
)

func file_protobuf_trade_proto_rawDescGZIP() []byte {
	file_protobuf_trade_proto_rawDescOnce.Do(func() {
		file_protobuf_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_trade_proto_rawDesc), len(file_protobuf_trade_proto_rawDesc)))
	})
	return file_protobuf_trade_proto_rawDescData
}

var file_protobuf_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_trade_proto_goTypes = []any{
	(*Trade)(nil),   // 0: app.Trade
	(Exchange)(0),   // 1: app.Exchange
	(Instrument)(0), // 2: app.Instrument
	(*Symbol)(nil),  // 3: app.Symbol
	(Side)(0),       // 4: app.Side
}
var file_protobuf_trade_proto_depIdxs = []int32{
	1, // 0: app.Trade.exchange:type_name -> app.Exchange
	2, // 1: app.Trade.instrument:type_name -> app.Instrument
	3, // 2: app.Trade.symbol:type_name -> app.Symbol
	4, // 3: app.Trade.side:type_name -> app.Side
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_trade_proto_init() }
func file_protobuf_trade_proto_init() {
	if File_protobuf_trade_proto != nil {
		return
	}
	file_protobuf_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_trade_proto_rawDesc), len(file_protobuf_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_trade_proto_goTypes,
		DependencyIndexes: file_protobuf_trade_proto_depIdxs,
		MessageInfos:      file_protobuf_trade_proto_msgTypes,
	}.Build()
	File_protobuf_trade_proto = out.File
	file_protobuf_trade_proto_goTypes = nil
	file_protobuf_trade_proto_depIdxs = nil
}
