// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: protobuf/example/example.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandomNumberMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomNumberMessage) Reset() {
	*x = RandomNumberMessage{}
	mi := &file_protobuf_example_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomNumberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumberMessage) ProtoMessage() {}

func (x *RandomNumberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_example_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumberMessage.ProtoReflect.Descriptor instead.
func (*RandomNumberMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_example_example_proto_rawDescGZIP(), []int{0}
}

func (x *RandomNumberMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RandomNumberMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_protobuf_example_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_example_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_example_example_proto_rawDescGZIP(), []int{1}
}

func (x *SumRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SumRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sum           int64                  `protobuf:"varint,2,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_protobuf_example_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_example_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_example_example_proto_rawDescGZIP(), []int{2}
}

func (x *SumResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SumResponse) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_protobuf_example_example_proto protoreflect.FileDescriptor

const file_protobuf_example_example_proto_rawDesc = "" +
	"\n" +
	"\x1eprotobuf/example/example.proto\x12\aexample\";\n" +
	"\x13RandomNumberMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"4\n" +
	"\n" +
	"SumRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"/\n" +
	"\vSumResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x03R\x03sumB?Z=github.com/BullionBear/sequex/internal/model/protobuf/exampleb\x06proto3"

var (
	file_protobuf_example_example_proto_rawDescOnce sync.Once
	file_protobuf_example_example_proto_rawDescData []byte
)

func file_protobuf_example_example_proto_rawDescGZIP() []byte {
	file_protobuf_example_example_proto_rawDescOnce.Do(func() {
		file_protobuf_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_example_example_proto_rawDesc), len(file_protobuf_example_example_proto_rawDesc)))
	})
	return file_protobuf_example_example_proto_rawDescData
}

var file_protobuf_example_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_example_example_proto_goTypes = []any{
	(*RandomNumberMessage)(nil), // 0: example.RandomNumberMessage
	(*SumRequest)(nil),          // 1: example.SumRequest
	(*SumResponse)(nil),         // 2: example.SumResponse
}
var file_protobuf_example_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_example_example_proto_init() }
func file_protobuf_example_example_proto_init() {
	if File_protobuf_example_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_example_example_proto_rawDesc), len(file_protobuf_example_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_example_example_proto_goTypes,
		DependencyIndexes: file_protobuf_example_example_proto_depIdxs,
		MessageInfos:      file_protobuf_example_example_proto_msgTypes,
	}.Build()
	File_protobuf_example_example_proto = out.File
	file_protobuf_example_example_proto_goTypes = nil
	file_protobuf_example_example_proto_depIdxs = nil
}
