// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: example/sum.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_example_sum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_sum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_example_sum_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NSum          int64                  `protobuf:"varint,1,opt,name=n_sum,json=nSum,proto3" json:"n_sum,omitempty"`
	NCount        int64                  `protobuf:"varint,2,opt,name=n_count,json=nCount,proto3" json:"n_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_example_sum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_sum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_example_sum_proto_rawDescGZIP(), []int{1}
}

func (x *SumResponse) GetNSum() int64 {
	if x != nil {
		return x.NSum
	}
	return 0
}

func (x *SumResponse) GetNCount() int64 {
	if x != nil {
		return x.NCount
	}
	return 0
}

var File_example_sum_proto protoreflect.FileDescriptor

const file_example_sum_proto_rawDesc = "" +
	"\n" +
	"\x11example/sum.proto\x12\x03rng\"$\n" +
	"\n" +
	"SumRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\";\n" +
	"\vSumResponse\x12\x13\n" +
	"\x05n_sum\x18\x01 \x01(\x03R\x04nSum\x12\x17\n" +
	"\an_count\x18\x02 \x01(\x03R\x06nCountBGZEgithub.com/BullionBear/sequex/internal/model/protobuf/example;exampleb\x06proto3"

var (
	file_example_sum_proto_rawDescOnce sync.Once
	file_example_sum_proto_rawDescData []byte
)

func file_example_sum_proto_rawDescGZIP() []byte {
	file_example_sum_proto_rawDescOnce.Do(func() {
		file_example_sum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_sum_proto_rawDesc), len(file_example_sum_proto_rawDesc)))
	})
	return file_example_sum_proto_rawDescData
}

var file_example_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_sum_proto_goTypes = []any{
	(*SumRequest)(nil),  // 0: rng.SumRequest
	(*SumResponse)(nil), // 1: rng.SumResponse
}
var file_example_sum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_sum_proto_init() }
func file_example_sum_proto_init() {
	if File_example_sum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_sum_proto_rawDesc), len(file_example_sum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_sum_proto_goTypes,
		DependencyIndexes: file_example_sum_proto_depIdxs,
		MessageInfos:      file_example_sum_proto_msgTypes,
	}.Build()
	File_example_sum_proto = out.File
	file_example_sum_proto_goTypes = nil
	file_example_sum_proto_depIdxs = nil
}
